// Fixed public pages that aren't driven by a database table (hub pages,
// "School" sub-pages, etc). Kept in sync manually with the routes under
// src/app/ and the editor sections listed in src/app/studio/page.tsx.
export const INTERNAL_PAGES: { href: string; label: string }[] = [
  { href: "/", label: "Home page" },
  { href: "/education-programs", label: "Education Programs — hub page" },
  { href: "/education-programs/nature-life-courses", label: "Nature & Outdoor Courses — hub page" },
  { href: "/short-courses", label: "Short Courses — hub page" },
  { href: "/summer-courses", label: "Summer Courses — hub page" },
  { href: "/summer-courses-practical-info", label: "Practical Info Summer Courses" },
  { href: "/evening-courses", label: "Evening Courses — hub page" },
  { href: "/news", label: "News — hub page" },
  { href: "/participant-stories", label: "Participant Stories — hub page" },
  { href: "/venues", label: "Venues — hub page" },
  { href: "/about", label: "School — hub page" },
  { href: "/about/apply", label: "Admission Periods" },
  { href: "/about/association", label: "Association" },
  { href: "/about/history", label: "History" },
  { href: "/about/careers", label: "Job Openings" },
  { href: "/boarding", label: "Boarding" },
  { href: "/about/study-guidance", label: "Study Guidance" },
  { href: "/about/student-support", label: "Student Support" },
  { href: "/about/student-rights", label: "Student Rights" },
  { href: "/about/term-dates", label: "Term Dates" },
  { href: "/about/report-issue", label: "Report an Issue" },
  { href: "/folk-education", label: "Folk Education" },
  { href: "/contact", label: "Contact Page" },
  { href: "/restaurant", label: "The Restaurant" },
  { href: "/study-motivation-course", label: "Study-Motivating Folk High School (short course)" },
  { href: "/mental-health-first-aid", label: "Mental Health First Aid (short course)" },
];
