#!/usr/bin/env node
// Generates docs/data-model.md from src/lib/db/schema.ts — a Mermaid ERD of the
// tables that actually have foreign keys, plus a compact listing of the
// singleton *Content tables that don't. Re-run with `npm run docs:erd`.
//
// The parse is deliberately regex-based rather than a TypeScript AST walk:
// schema.ts is one flat list of `export const x = sqliteTable(...)` blocks, so
// splitting on `export const` is enough and keeps this script dependency-free.
import { readFileSync, writeFileSync } from "node:fs";

const SCHEMA_PATH = "src/lib/db/schema.ts";
const OUT_PATH = "docs/data-model.md";

const source = readFileSync(SCHEMA_PATH, "utf8");

// ─── Parse ────────────────────────────────────────────────────────────────────

// One region per `export const` declaration, running up to the next one.
const regions = source.split(/^export const /m).slice(1);

const tables = []; // { varName, dbName, columns: [...] }

for (const region of regions) {
  const header = region.match(/^(\w+)\s*=\s*sqliteTable\(\s*"([^"]+)"/);
  if (!header) continue; // not a table (type alias, helper, ...)
  const [, varName, dbName] = header;

  // Column declarations sit at exactly two spaces of indentation; continuation
  // lines (.references(...) spread over lines) are indented deeper.
  const columnRe = /^ {2}(\w+):\s*(text|integer|real|blob)\(/gm;
  const starts = [];
  let m;
  while ((m = columnRe.exec(region)) !== null) {
    starts.push({ name: m[1], type: m[2], index: m.index });
  }

  const columns = starts.map((col, i) => {
    const body = region.slice(col.index, starts[i + 1]?.index ?? region.length);
    const ref = body.match(/=>\s*(\w+)\.(\w+)/);
    return {
      name: col.name,
      type: col.type,
      notNull: /\.notNull\(\)/.test(body),
      unique: /\.unique\(\)/.test(body),
      primaryKey: /\.primaryKey\(\)/.test(body),
      references: ref ? { table: ref[1], column: ref[2] } : null,
      onDelete: body.match(/onDelete:\s*"([^"]+)"/)?.[1] ?? null,
    };
  });

  // Composite primary keys on the join tables: primaryKey({ columns: [t.a, t.b] })
  const composite = region.match(/primaryKey\(\{\s*columns:\s*\[([^\]]+)\]/);
  if (composite) {
    for (const ref of composite[1].matchAll(/\w+\.(\w+)/g)) {
      const target = columns.find((c) => c.name === ref[1]);
      if (target) target.primaryKey = true;
    }
  }

  tables.push({ varName, dbName, columns });
}

const dbNameOf = new Map(tables.map((t) => [t.varName, t.dbName]));

// ─── Derive relations ─────────────────────────────────────────────────────────

const relations = [];
for (const table of tables) {
  for (const column of table.columns) {
    if (!column.references) continue;
    const parent = dbNameOf.get(column.references.table);
    if (!parent) continue; // reference to something outside this file
    relations.push({
      parent,
      child: table.dbName,
      column: column.name,
      notNull: column.notNull,
      onDelete: column.onDelete,
    });
  }
}

// Columns shaped like foreign keys that carry no constraint. These are real
// links the ERD cannot draw — sidebarProfileIds is a JSON array of Profile ids,
// programId/summerCourseId point at Course — plus a few ids owned by external
// systems (Better Auth, SchoolSoft) that are not relations at all.
const softReferences = [];
for (const table of tables) {
  for (const column of table.columns) {
    if (column.references || !/(Id|Ids)$/.test(column.name)) continue;
    softReferences.push({ table: table.dbName, column: column.name, type: column.type });
  }
}

const related = new Set(relations.flatMap((r) => [r.parent, r.child]));
const core = tables.filter((t) => related.has(t.dbName));
const standalone = tables.filter((t) => !related.has(t.dbName));

// ─── Render ───────────────────────────────────────────────────────────────────

const keyFlag = (c) => (c.primaryKey ? "PK" : c.references ? "FK" : c.unique ? "UK" : "");

const lines = [];
lines.push("<!-- Generated by scripts/generate-erd.mjs — do not edit by hand.");
lines.push("     Run `npm run docs:erd` after changing src/lib/db/schema.ts. -->");
lines.push("");
lines.push("# Data model");
lines.push("");
lines.push(
  `${tables.length} tables in [schema.ts](../src/lib/db/schema.ts): ` +
    `**${core.length}** carry foreign keys and form the relational core below, ` +
    `**${standalone.length}** are standalone rows with no relations at all — ` +
    "mostly the per-page singleton `*Content` tables, listed at the end.",
);
lines.push("");
lines.push("## Relational core");
lines.push("");
lines.push("```mermaid");
lines.push("erDiagram");

for (const r of relations) {
  // `||--o{` = every child must have a parent; `|o--o{` = the FK is nullable.
  const cardinality = r.notNull ? "||--o{" : "|o--o{";
  const label = r.onDelete ? `${r.column} (${r.onDelete})` : r.column;
  lines.push(`    ${r.parent} ${cardinality} ${r.child} : "${label}"`);
}
lines.push("");

for (const table of core) {
  // Only key columns go in the diagram — the full list is in the tables below.
  // Drawing all ~48 columns of Course would make the graph unreadable.
  const keys = table.columns.filter((c) => keyFlag(c));
  lines.push(`    ${table.dbName} {`);
  for (const c of keys) lines.push(`        ${c.type} ${c.name} ${keyFlag(c)}`);
  lines.push(`        int columns "${table.columns.length} total"`);
  lines.push("    }");
}
lines.push("```");
lines.push("");
lines.push("### Columns");
lines.push("");

for (const table of core) {
  lines.push(`#### ${table.dbName}`);
  lines.push("");
  lines.push("| Column | Type | Key | Null | References |");
  lines.push("|---|---|---|---|---|");
  for (const c of table.columns) {
    const ref = c.references
      ? `${dbNameOf.get(c.references.table) ?? c.references.table}.${c.references.column}` +
        (c.onDelete ? ` — on delete ${c.onDelete}` : "")
      : "";
    lines.push(
      `| \`${c.name}\` | ${c.type} | ${keyFlag(c)} | ${c.notNull || c.primaryKey ? "" : "nullable"} | ${ref} |`,
    );
  }
  lines.push("");
}

lines.push("## Soft references");
lines.push("");
lines.push(
  "Columns named like foreign keys but declared without a `references()` " +
    "constraint, so they appear nowhere in the diagram above. Some are genuine " +
    "in-database links the ERD cannot express (`sidebarProfileIds` holds a JSON " +
    "array of `Profile` ids); others are identifiers owned by an external system " +
    "and are not relations at all. Verify before treating any of them as a join.",
);
lines.push("");
lines.push("| Table | Column | Type |");
lines.push("|---|---|---|");
for (const s of softReferences) {
  lines.push(`| ${s.table} | \`${s.column}\` | ${s.type} |`);
}
lines.push("");
lines.push("## Standalone tables");
lines.push("");
lines.push(
  "No foreign keys in either direction. The `*Content` tables are single-row " +
    "page content holders — near-identical in shape, which is why they are " +
    "listed rather than drawn.",
);
lines.push("");
lines.push("| Table | Columns | Column names |");
lines.push("|---|---|---|");
for (const table of standalone) {
  const names = table.columns.map((c) => `\`${c.name}\``).join(", ");
  lines.push(`| ${table.dbName} | ${table.columns.length} | ${names} |`);
}
lines.push("");

writeFileSync(OUT_PATH, lines.join("\n"));
console.log(
  `${OUT_PATH}: ${tables.length} tables (${core.length} related, ${standalone.length} standalone), ` +
    `${relations.length} foreign keys, ${softReferences.length} soft references`,
);
